version: "3.6"
services:
  prometheus:
    image: prom/prometheus
    container_name: xrksudy.monitor.prometheus
    restart: always
    ports:
      - "${PROMETHEUS_PORT}:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - net-prom

networks:
  net-prom:
