version: "3.6"
services:
  gitlab:
    image: "gitlab/gitlab-ce:latest"
    container_name: xrksudy.devops.gitlab
    restart: always
    hostname: "${GITLAB_WEB}"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.devfan.site:${GITLAB_WEB_PORT}'
        gitlab_rails['time_zone'] = 'Asia/Shanghai'
        gitlab_rails['gitlab_shell_ssh_port'] = ${GITLAB_SSH_PORT}
    ports:
      - "${GITLAB_WEB_PORT}:${GITLAB_WEB_PORT}"
      - "${GITLAB_SSH_PORT}:22"
    volumes:
      - "$GITLAB_HOME/config:/etc/gitlab"
      - "$GITLAB_HOME/logs:/var/log/gitlab"
      - "$GITLAB_HOME/data:/var/opt/gitlab"
    networks:
      - gitlab-network
  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: xrksudy.devops.gitlab.runner
    restart: always
    ports:
      - "${GITLAB_RUNNER_PORT}:8093"
    volumes:
      - "${DOCKER_RUNNING_PATH}:/var/run/docker.sock"
      - "${GITLAB_RUNNER_CONFIG}:/etc/gitlab-runner"
    networks:
      - gitlab-network

networks:
  gitlab-network:
    name: gitlab-network
