version: "3"
services:
  web:
    image: "gitlab/gitlab-ce:latest"
    container_name: xrksudy.devops.gitlab
    restart: always
    hostname: "${GITLAB_WEB}"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.devfan.site:${GITLAB_WEB_PORT}'
        gitlab_rails['time_zone'] = 'Asia/Shanghai'
        gitlab_rails['gitlab_shell_ssh_port'] = ${GITLAB_SSH_PORT}
    ports:
      - "${GITLAB_WEB_PORT}:${GITLAB_WEB_PORT}"
      - "${GITLAB_SSH_PORT}:22"
    volumes:
      - "$GITLAB_HOME/config:/etc/gitlab"
      - "$GITLAB_HOME/logs:/var/log/gitlab"
      - "$GITLAB_HOME/data:/var/opt/gitlab"
