version: "3"
services:
  es-master:
    container_name: xrksudy-es-master
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
    restart: always
    ports:
      - 9008:9008
      - 9009:9009
    volumes:
      - ./es-master.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ${ES_DATA}:/usr/share/elasticsearch/data
      - ${ES_LOG}:/usr/share/elasticsearch/logs
      - ../es-plugin/:/usr/share/elasticsearch/plugins/
    environment:
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    networks:
      - default
