version: "3"
services:
  mysql:
    container_name: xrksudy.mysql.stand-alone
    build: ./mysql
    restart: always
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - "${MYSQL_DIR}/data:/var/lib/mysql"
      - "${MYSQL_DIR}/log:/var/log/mysql"
      # - "./init:/docker-entrypoint-initdb.d"  # 初始化数据
      - /etc/localtime:/etc/localtime ## 同步时间
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=${MYSQL_ROOT_PASSWORD}
      timeout: 20s
      retries: 10
    networks:
      - default
