auth_enabled: false

server:
  http_listen_port: 4100
  grpc_listen_port: 4096

common:
  path_prefix: /data/devops/loki
  storage:
    filesystem:
      chunks_directory: /data/devops/loki/chunks
      rules_directory: /data/devops/loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://localhost:4093