version: "3"
services:
  mysql:
    container_name: xrksudy.mysql
    build: ./mysql
    # image: mysql:5.7.22
    restart: always
    ports:
      - 3306:3306
    volumes:
      # - ./mysql/conf/my.cnf:/etc/mysql/my.cnf:rw
      # - "${MYSQL_DIR}/conf.d:/etc/mysql/conf.d"
      - "${MYSQL_DIR}/data:/var/lib/mysql"
      - "${MYSQL_DIR}/log:/var/log/mysql"
      # - "./init:/docker-entrypoint-initdb.d"  # 初始化数据
      - /etc/localtime:/etc/localtime ## 同步时间
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=${MYSQL_ROOT_PASSWORD}
      timeout: 20s
      retries: 10
    networks:
      - default
  redis:
    container_name: xrksudy.redis
    build: ./redis
    # 指定镜像
    # image: redis:4
    ports:
      # 端口映射
      - 6379:6379
    volumes:
      # 目录映射
      # - "${REDIS_DIR}/conf:/usr/local/etc/redis"
      - "${REDIS_DIR}/data:/data"
      # - "${REDIS_DIR}/log:/data"
    #command:
    # 执行的命令
    # redis-server
    networks:
      - default

  # https://stackoverflow.com/questions/42912755/how-to-create-a-db-for-mongodb-container-on-start-up
  mongodb:
    container_name: xrksudy.mongodb
    build: ./mongodb
    #image: 'bitnami/mongodb:4.0'
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb/conf/mongod.conf:/etc/mongod.conf
      #- ./mongodb/init/:/docker-entrypoint-initdb.d/
      - ${MONGODB_DIR}/data/:/data/db/
      - ${MONGODB_DIR}/log:/var/log/mongodb/
      - /etc/localtime:/etc/localtime
    command: --auth
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=xrksudy-discover-!@
    networks:
      - default
