version: "3"
services:
  glances:
    container_name: xrksudy_glances
    image: nicolargo/glances
    volumes:
      # - ./data:/etc/glances
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - GLANCES_OPT=-w
    ports:
      - "61208:61208"
      - "61209:61209"
    restart: always
