version: "3.6"
services:
  node-exporter:
    image: prom/node-exporter
    container_name: xrksudy.monitor.node-exporter
    restart: always
    ports:
      - "${NODE_EXPORTER_PORT}:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
      - net-ne

networks:
  net-ne:
